export const WORD_CATEGORIES = {
    ANIMALS: {
        EASY: ['CAT', 'DOG', 'BAT', 'PIG', 'COW', 'FOX', 'OWL', 'BEE', 'ANT', 'YAK', 'EWE', 'GNU', 'EMU', 'RAM', 'HEN', 'CUB', 'EEL', 'FLY', 'JAY', 'KOI'],
        MEDIUM: ['TIGER', 'ZEBRA', 'HORSE', 'SHEEP', 'PANDA', 'KOALA', 'EAGLE', 'SHARK', 'WHALE', 'SNAKE', 'CRANE', 'BISON', 'MOOSE', 'LLAMA', 'HYENA', 'GECKO', 'ROBIN', 'TROUT', 'VIPER', 'SQUAB'],
        HARD: ['ELEPHANT', 'GIRAFFE', 'DOLPHIN', 'PENGUIN', 'CHEETAH', 'GORILLA', 'OCTOPUS', 'BUTTERFLY', 'KANGAROO', 'CROCODILE', 'FLAMINGO', 'PLATYPUS', 'LEOPARD', 'SCORPION', 'ALBATROSS', 'WOLVERINE', 'CHAMELEON', 'PORCUPINE', 'MANDRILL', 'SALAMANDER']
    },
    NATURE: {
        EASY: ['SUN', 'SKY', 'SEA', 'BUD', 'DEW', 'FOG', 'MUD', 'ICE', 'GAS', 'AIR', 'OAK', 'ASH', 'ELM', 'FIG', 'IVY', 'SOD', 'ORE', 'TAR', 'SAP', 'DIM'],
        MEDIUM: ['RIVER', 'CLOUD', 'STORM', 'GRASS', 'FLOWER', 'STONE', 'WATER', 'BEACH', 'NIGHT', 'PLANT', 'FROST', 'CREEK', 'ALGAE', 'BLAZE', 'DUNES', 'GROVE', 'RIDGE', 'MARSH', 'FJORD', 'THORN'],
        HARD: ['MOUNTAIN', 'VOLCANO', 'TORNADO', 'THUNDER', 'RAINBOW', 'FOREST', 'DESERT', 'GLACIER', 'SUNRISE', 'BLOSSOM', 'RAVINE', 'CANYON', 'TUNDRA', 'SAVANNA', 'WETLAND', 'MONSOON', 'TYPHOON', 'BLIZZARD', 'AVALANCHE', 'PENINSULA']
    },
    OBJECTS: {
        EASY: ['BAT', 'BOX', 'CAN', 'FAN', 'HAT', 'JAR', 'KEY', 'MAP', 'PAN', 'TAG', 'CUP', 'PIN', 'RUG', 'JUG', 'MAT', 'LOG', 'POT', 'NET', 'ROD', 'WIG'],
        MEDIUM: ['TABLE', 'CHAIR', 'CLOCK', 'PHONE', 'GLASS', 'PLATE', 'SPOON', 'BRUSH', 'PAPER', 'WATCH', 'TOWEL', 'SHELF', 'CANDLE', 'PILLOW', 'BOTTLE', 'WALLET', 'MIRROR', 'NEEDLE', 'BUCKET', 'HELMET'],
        HARD: ['COMPUTER', 'KEYBOARD', 'MONITOR', 'UMBRELLA', 'SCISSORS', 'TRUMPET', 'GUITAR', 'CAMERA', 'LADDER', 'WHISTLE', 'LANTERN', 'COMPASS', 'THERMOS', 'TELESCOPE', 'MICROSCOPE', 'BAROMETER', 'BRIEFCASE', 'FLASHLIGHT', 'CALCULATOR', 'MICROPHONE']
    },
    ACTIONS: {
        EASY: ['RUN', 'SIT', 'EAT', 'FLY', 'CRY', 'MIX', 'DIG', 'HOP', 'CUT', 'NAP', 'DIP', 'ROW', 'BEG', 'TAP', 'ZIP', 'NOD', 'POP', 'SAW', 'WAX', 'BOW'],
        MEDIUM: ['DANCE', 'SLEEP', 'WRITE', 'DRINK', 'LAUGH', 'CLIMB', 'SWIM', 'DRIVE', 'PAINT', 'SMILE', 'THROW', 'CATCH', 'SHOUT', 'PLANT', 'BUILD', 'CARRY', 'BRUSH', 'SHAKE', 'MARCH', 'FLOAT'],
        HARD: ['EXPLORE', 'WHISPER', 'STRETCH', 'BOUNCE', 'SPRINT', 'JUGGLE', 'SKETCH', 'LISTEN', 'WANDER', 'TRAVEL', 'BALANCE', 'STUMBLE', 'SCATTER', 'GLITTER', 'IMAGINE', 'NAVIGATE', 'CELEBRATE', 'DISCOVER', 'REMEMBER', 'BREATHE']
    }
};
